# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main_Window(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(673, 539)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 20, 141, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_ok = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_ok.setStyleSheet("\n"
"background-color: rgb(0, 170, 0);\n"
"border-color: rgb(85, 0, 255);")
        self.btn_ok.setObjectName("btn_ok")
        self.horizontalLayout.addWidget(self.btn_ok)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(40, 60, 141, 441))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.listWidget = QtWidgets.QListWidget(self.horizontalLayoutWidget_2)
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout_2.addWidget(self.listWidget)
        self.btn_left = QtWidgets.QPushButton(Form)
        self.btn_left.setGeometry(QtCore.QRect(190, 20, 121, 31))
        self.btn_left.setStyleSheet("background-color: rgb(170, 0, 255);\n"
"border-color: rgb(85, 170, 255);")
        self.btn_left.setObjectName("btn_left")
        self.btn_right = QtWidgets.QPushButton(Form)
        self.btn_right.setGeometry(QtCore.QRect(322, 20, 111, 31))
        self.btn_right.setStyleSheet("background-color: rgb(170, 0, 255);\n"
"border-color: rgb(85, 170, 255);")
        self.btn_right.setObjectName("btn_right")
        self.btn_up = QtWidgets.QPushButton(Form)
        self.btn_up.setGeometry(QtCore.QRect(440, 20, 101, 31))
        self.btn_up.setStyleSheet("background-color: rgb(170, 0, 255);\n"
"border-color: rgb(85, 170, 255);")
        self.btn_up.setObjectName("btn_up")
        self.btn_resise = QtWidgets.QPushButton(Form)
        self.btn_resise.setGeometry(QtCore.QRect(192, 470, 111, 31))
        self.btn_resise.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border-color: rgb(255, 255, 0);")
        self.btn_resise.setObjectName("btn_resise")
        self.btn_sharp = QtWidgets.QPushButton(Form)
        self.btn_sharp.setGeometry(QtCore.QRect(310, 470, 201, 31))
        self.btn_sharp.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border-color: rgb(255, 255, 0);")
        self.btn_sharp.setObjectName("btn_sharp")
        self.btn_bw = QtWidgets.QPushButton(Form)
        self.btn_bw.setGeometry(QtCore.QRect(520, 470, 131, 31))
        self.btn_bw.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border-color: rgb(255, 255, 0);")
        self.btn_bw.setObjectName("btn_bw")
        self.btn_flip = QtWidgets.QPushButton(Form)
        self.btn_flip.setGeometry(QtCore.QRect(550, 20, 101, 31))
        self.btn_flip.setStyleSheet("background-color: rgb(170, 0, 255);\n"
"border-color: rgb(85, 170, 255);")
        self.btn_flip.setObjectName("btn_flip")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(200, 60, 451, 391))
        self.label.setText("")
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_ok.setText(_translate("Form", "Open folder"))
        self.btn_left.setText(_translate("Form", "Left"))
        self.btn_right.setText(_translate("Form", "Right"))
        self.btn_up.setText(_translate("Form", "UP"))
        self.btn_resise.setText(_translate("Form", "Resise"))
        self.btn_sharp.setText(_translate("Form", "Sharp"))
        self.btn_bw.setText(_translate("Form", "B/W"))
        self.btn_flip.setText(_translate("Form", "Flip"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Main_Window()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
